export const roulettesList = [
  { name: 'Ruleta #1', minimumBalance: '100' },
  { name: 'Ruleta #2', minimumBalance: '100' },
  { name: 'Ruleta #3', minimumBalance: '100' },
  { name: 'Ruleta #4', minimumBalance: '100' },
  { name: 'Ruleta #5', minimumBalance: '100' },
  { name: 'Ruleta #6', minimumBalance: '100' },
  { name: 'Ruleta #7', minimumBalance: '100' },
  { name: 'Ruleta #8', minimumBalance: '100' },
  { name: 'Ruleta #9', minimumBalance: '100' },
  { name: 'Ruleta #10', minimumBalance: '100' },
  { name: 'Ruleta #11', minimumBalance: '100' },
  { name: 'Ruleta #12', minimumBalance: '100' },
  { name: 'Ruleta #13', minimumBalance: '100' },
  { name: 'Ruleta #14', minimumBalance: '100' },
  { name: 'Ruleta #15', minimumBalance: '100' },
  { name: 'Ruleta #16', minimumBalance: '100' },
  { name: 'Ruleta #17', minimumBalance: '100' },
  { name: 'Ruleta #18', minimumBalance: '100' },
  { name: 'Ruleta #19', minimumBalance: '100' },
  { name: 'Ruleta #20', minimumBalance: '100' },
];
